Traceback (most recent call last):
  File "C:\Users\beck\miniforge3\envs\jubook\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "C:\Users\beck\miniforge3\envs\jubook\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\beck\miniforge3\envs\jubook\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\beck\miniforge3\envs\jubook\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\beck\miniforge3\envs\jubook\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "C:\Users\beck\miniforge3\envs\jubook\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\beck\miniforge3\envs\jubook\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\beck\miniforge3\envs\jubook\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas

df_sol = pandas.read_excel('SolarNorm.xlsx')#, sheet_name='Employees')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_20816\2731352093.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mpandas[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [0mdf_sol[0m [1;33m=[0m [0mpandas[0m[1;33m.[0m[0mread_excel[0m[1;33m([0m[1;34m'SolarNorm.xlsx'[0m[1;33m)[0m[1;31m#, sheet_name='Employees')[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

