Traceback (most recent call last):
  File "C:\Users\beck\miniforge3\envs\Jubook\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "C:\Users\beck\miniforge3\envs\Jubook\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\beck\miniforge3\envs\Jubook\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\beck\miniforge3\envs\Jubook\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\beck\miniforge3\envs\Jubook\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "C:\Users\beck\miniforge3\envs\Jubook\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\beck\miniforge3\envs\Jubook\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\beck\miniforge3\envs\Jubook\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

def Planck(lam, T): # Function for Planck law
    # Physikalische GrÃ¶ÃŸen alle in SI Einheiten: W, s, m, K
    h = 6.626e-34        # Plancksches Wirkungsquantum
    c = 3e8              # Lichtgeschwindigkeit
    k = 1.38e-23         # Boltzmann-Konstante

    c1  = 2*np.pi*c**2*h
    c2  = c*h/k

    I_lam = c1 / (lam**5 * (np.exp(c2 / (lam*T)) - 1))                            # spektrale Strahlungsflussdichte
    return I_lam

min_L =  200e-9
max_L = 3000e-9
dL    =    5e-9
NL    = int((max_L - min_L) / dL + 1)
lam   = np.linspace(min_L, max_L, NL)
T     = 5800
I     = SolRad(lam=lam, T=T)

fig = plt.figure(figsize=(13, 3))
title = 'Spectral Solar Radiation Density, T =' + str(T) + 'K'
plt.title(title)
plt.xlabel('$\lambda$ / nm')
plt.ylabel('$I(\lambda)$ / (W/mÂ²/nm)')
plt.plot(lam * 1e9, I)
plt.grid()
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_29216\4161474671.py[0m in [0;36m<module>[1;34m[0m
[0;32m     20[0m [0mlam[0m   [1;33m=[0m [0mnp[0m[1;33m.[0m[0mlinspace[0m[1;33m([0m[0mmin_L[0m[1;33m,[0m [0mmax_L[0m[1;33m,[0m [0mNL[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     21[0m [0mT[0m     [1;33m=[0m [1;36m5800[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 22[1;33m [0mI[0m     [1;33m=[0m [0mSolRad[0m[1;33m([0m[0mlam[0m[1;33m=[0m[0mlam[0m[1;33m,[0m [0mT[0m[1;33m=[0m[0mT[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     23[0m [1;33m[0m[0m
[0;32m     24[0m [0mfig[0m [1;33m=[0m [0mplt[0m[1;33m.[0m[0mfigure[0m[1;33m([0m[0mfigsize[0m[1;33m=[0m[1;33m([0m[1;36m13[0m[1;33m,[0m [1;36m3[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'SolRad' is not defined
NameError: name 'SolRad' is not defined

